export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_TO_CART="REMOVE_TO_CART";

export const ORDER_REQUEST="ORDER_REQUEST"
export const ORDER_SUCCESS="ORDER_SUCCESS"
export const ORDER_FAIL="ORDER_FAIL"

export const ORDER_LIST_REQUEST='PRODUCT_LIST_REQUEST'
export const ORDER_LIST_SUCCESS='PRODUCT_LIST_SUCCESS'
export const ORDER_LIST_FAIL="PRODUCT_LIST_FAIL"

export const DELETE_ORDER="DELETE_ORDER"